"""SuperMemory uploader for profile data.

This module uploads markdown files to SuperMemory for knowledge graph storage.
API: https://api.supermemory.ai/v3/documents
Docs: https://supermemory.ai/docs/add-memories/examples/file-upload
"""

import os
import logging
import requests
from pathlib import Path
from typing import Optional, Dict, Any

logger = logging.getLogger(__name__)

SUPERMEMORY_API_URL = "https://api.supermemory.ai/v3/documents/file"


def upload_markdown_to_supermemory(
    markdown_path: Path,
    container_tags: str = "profiles",
    api_key: Optional[str] = None,
) -> Dict[str, Any]:
    """Upload a markdown file to SuperMemory.

    Parameters
    ----------
    markdown_path : Path
        Path to the markdown file generated by Crawl4AI
    container_tags : str
        Tags to organize the memory (default: "profiles")
    api_key : Optional[str]
        SuperMemory API key (defaults to SUPERMEMORY_API_KEY env var)

    Returns
    -------
    Dict[str, Any]
        Response from SuperMemory API containing the memory ID

    Raises
    ------
    FileNotFoundError
        If the markdown file doesn't exist
    RuntimeError
        If API key is missing
    requests.HTTPError
        If the API request fails
    """
    if not markdown_path.exists():
        raise FileNotFoundError(f"Markdown file not found: {markdown_path}")

    # Get API key from parameter or environment
    api_key = api_key or os.getenv("SUPERMEMORY_API_KEY")
    if not api_key:
        raise RuntimeError(
            "SuperMemory API key not found. Set SUPERMEMORY_API_KEY environment variable "
            "or pass api_key parameter"
        )

    try:
        logger.info(f"Uploading {markdown_path} to SuperMemory...")
        
        # Prepare the file upload
        with open(markdown_path, 'rb') as file:
            files = {
                'file': (markdown_path.name, file, 'text/markdown')
            }
            data = {
                'containerTags': container_tags
            }
            headers = {
                'Authorization': f'Bearer {api_key}'
            }
            
            # Upload to SuperMemory API
            response = requests.post(
                SUPERMEMORY_API_URL,
                files=files,
                data=data,
                headers=headers,
                timeout=30
            )
            
            # Raise exception for bad status codes
            response.raise_for_status()
            
            # Parse response
            result = response.json()
            memory_id = result.get('id', 'unknown')
            
            logger.info(f"✓ Successfully uploaded to SuperMemory with ID: {memory_id}")
            return result
        
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to upload to SuperMemory: {e}")
        if hasattr(e, 'response') and e.response is not None:
            logger.error(f"Response: {e.response.text}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error during SuperMemory upload: {e}")
        raise
